name: "TTSModManager Local Action"
description: "Run TTSModManager with custom arguments"

inputs:
  output-file:
    description: "Output JSON file name for the mod"
    required: false
    default: "output.json"

  moddir:
    description: "Directory containing objects, scripts, and UI"
    required: false
    default: "."

  config:
    description: "Path to mod configuration file"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "🏗️  Running TTSModManager"
        echo "📁 moddir: ${{ inputs.moddir }}"
        echo "⚙️ config: ${{ inputs.config }}"
        echo "📝 output: ${{ inputs.output-file }}"

        CMD="TTSModManager --moddir='${{ inputs.moddir }}' --output='${{ inputs.output-file }}'"

        if [ -n "${{ inputs.config }}" ]; then
          CMD="$CMD --config='${{ inputs.config }}'"
        fi

        echo "🔧 Command: $CMD"
        eval $CMD
