name: build-mod

on:
  release:
    types: [created]

permissions:
  contents: write
  actions: read

jobs:
  build-the-mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate mod named after tag
        uses: ./github/actions/TTSModManager
        with:
          output-file: mod-${{ github.ref_name }}.json