name: build-mod

on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:

permissions:
  contents: write
  actions: read

jobs:
  build-the-mod:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧱 Run TTSModManager (local action)
        uses: ./.github/actions/TTSModManager
        with:
          moddir: .
          config: ./modfile.json
          output-file: mod-${{ github.ref_name }}.json

      - name: 📂 Show generated files
        run: ls -lh

      - name: 📤 Upload mod artifact
        uses: actions/upload-artifact@v3
        with:
          name: tts-mod
          path: mod-${{ github.ref_name }}.json
