name: build-mod

on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:

permissions: read-all

jobs:
  build-the-mod:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run local TTSModManager Action
        uses: ./.github/actions/TTSModManager
