name: Run TTSModManager After Merge

on:
  pull_request:
    types: [closed]

jobs:
  run-ttsmodmanager:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read SaveName from config.json
        id: version
        run: |
          VERSION=$(jq -r '.SaveName' config.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download TTSModManager
        run: |
          mkdir -p ./TTSModManager
          curl -L -o ./TTSModManager/TTSModManager \
            https://github.com/argonui/TTSModManager/releases/download/v1.3/TTSModManager-Linux
          chmod +x ./TTSModManager/TTSModManager


      - name: Run TTSModManager
        run: |
          ./TTSModManager/TTSModManager \
            --moddir="." \
            --modfile="saves/AH ${{ steps.version.outputs.version }}.json"

